# Generated by Django 2.0.4 on 2019-05-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=50)),
                ('picture_url', models.ImageField(blank=True, max_length=200, null=True, upload_to='image')),
            ],
            options={
                'db_table': 'web-site',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='WebSiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'website-type',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='website',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecenter.WebSiteType'),
        ),
    ]
