# Generated by Django 2.0.4 on 2019-05-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managecenter', '0002_auto_20190507_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='picture_url',
            new_name='logo_url',
        ),
    ]
