# Generated by Django 2.0.4 on 2019-05-08 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managecenter', '0003_auto_20190508_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetype',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
