# Generated by Django 2.0.4 on 2019-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecenter', '0004_auto_20190508_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitetype',
            options={},
        ),
        migrations.AddField(
            model_name='websitetype',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
